// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerMVC2_MJ.Data;

#nullable disable

namespace TallerMVC2_MJ.Migrations
{
    [DbContext(typeof(TallerMVC2_MJContext))]
    [Migration("20240417164916_InicioBdd")]
    partial class InicioBdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerMVC2_MJ.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("WithCheese")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Burger");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.Promo", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<int?>("BurgerId")
                        .HasColumnType("int");

                    b.Property<int>("BurguerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPromocion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoId");

                    b.HasIndex("BurgerId");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.Promo", b =>
                {
                    b.HasOne("TallerMVC2_MJ.Models.Burger", "Burger")
                        .WithMany("Promo")
                        .HasForeignKey("BurgerId");

                    b.Navigation("Burger");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.Burger", b =>
                {
                    b.Navigation("Promo");
                });
#pragma warning restore 612, 618
        }
    }
}
