// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TallerMVC2_MJ.Migrations
{
    [DbContext(typeof(mjburgerpersonalizado))]
    [Migration("20240602200312_burgerpersonalizado")]
    partial class burgerpersonalizado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerMVC2_MJ.Models.MJBurger", b =>
                {
                    b.Property<int>("MJBurgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MJBurgerId"));

                    b.Property<string>("MJName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MJPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MJWithCheese")
                        .HasColumnType("bit");

                    b.HasKey("MJBurgerId");

                    b.ToTable("MJBurger");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.MJPromo", b =>
                {
                    b.Property<int>("MJPromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MJPromoId"));

                    b.Property<int>("MJBurgerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MJFechaPromocion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MJPromoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MJPromoId");

                    b.HasIndex("MJBurgerId");

                    b.ToTable("MJPromo");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.MJPromo", b =>
                {
                    b.HasOne("TallerMVC2_MJ.Models.MJBurger", "MJBurger")
                        .WithMany("MJPromo")
                        .HasForeignKey("MJBurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MJBurger");
                });

            modelBuilder.Entity("TallerMVC2_MJ.Models.MJBurger", b =>
                {
                    b.Navigation("MJPromo");
                });
#pragma warning restore 612, 618
        }
    }
}
